src/veins/base/phyLayer/MappingUtils.h

remove badly written trap left over from mixim.
replace with meaningful exception.
this should clean up the compilation process a lot.

clean up nullptr-dereference compiler warning

---

src/veins/modules/mobility/traci/TraCICommandInterface.cc
src/veins/modules/mobility/traci/TraCICommandInterface.h

- Split up the enumerations for special values according to categories
(time, speed, position, lane)
- Add missing values to enums
- Use enum values as specified by TraCI (negative values)
- Fix usage of depart time: The default parameter indicated 'DEPART_NOW'
was used, its value corressponds to 'container triggered' but any
negative value will actually get mapped to 'triggered'.
- Change default depart time parameter to triggered, this expresses the
current behavior
- Add documentation

Clarify TraCI add vehicle interface

---

src/veins/modules/mobility/traci/TraCIScenarioManager.cc
src/veins/modules/mobility/traci/TraCIScenarioManager.h
src/veins/modules/mobility/traci/TraCIScenarioManagerForker.ned
src/veins/modules/mobility/traci/TraCIScenarioManagerLaunchd.ned

This signal enables other modules to be notified once the TraCIScenarioManager is initialzied. Previously the usual approach was to poll until `isConnected` returns true.

Add traci-initialized signal

---

src/veins/modules/mobility/traci/TraCIScenarioManager.ned
src/veins/modules/mobility/traci/TraCIScenarioManagerForker.ned
src/veins/modules/mobility/traci/TraCIScenarioManagerLaunchd.ned
src/veins/nodes/Scenario.ned

To avoid having duplicated code (i.e. parameters), all common parameters of the specific implementations for the TraCIScenarioManager are extracted to a base ned file.
Thus, the common code only has to touched once and specific code can co into the respective extending ned files (i.e. TraCIScenarioManagerLaunchd and TraCIScenarioManagerForker).

Add (base) ned file for TraCIScenarioManager

---

src/veins/modules/utility/SimpleTimerModule.cc
src/veins/modules/utility/SimpleTimerModule.h

The added module can be used as a base class instead of omnetpp::cSimpleModule to use timers.
There are three types of timers available:
- oneshot: Executed only once, at the specified time.
- repeating, by count: Repeated n-times. Each occurence is followed by an interval, the timers period.
- Repeating, interval based: A timer which repeats based on time boundaries. The start and end time can be omitted, to support open-ended timers.
The times which are passed can be given in relative (to the current simulation time) and absolute time. All timers can be cancelled at any time. Upon triggering, the timers execute a std::function based callback. Therefore, subclasses don't necessarily need to override cSimpleModule::handleMessage anymore if they to not receive any proper, i.e. networking …

Add a SimpleTimerModule

---

src/veins/modules/mac/ieee80211p/Mac1609_4.cc
src/veins/modules/mac/ieee80211p/Mac1609_4.h

This fixes the undisposed object after incorrect termination of the
simulation (thus finish is not called) and initializes pointers
correctly. Also the pointer variable is deleted (i.e. set to nullptr).
Excerpt from the [manual](https://omnetpp.org/doc/omnetpp/manual/#sec:simple-modules:initialize-and-finish)
> finish():
> 
> Record statistics. Do not delete anything or cancel timers -- all cleanup must be done in the destructor.
> 
> Destructor:
> 
> Delete everything which was allocated by new and is still held by the module class. With self-messages (timers), use the cancelAndDelete(msg) function! It is almost always wrong to just delete a self-message from the destructor, because it might be in the scheduled events list. The cancelAndDelete(msg) function checks for that first, and …

Handle self-messages according to omnetpp manual

---

src/veins/modules/mobility/traci/NetworkBoundary.cc
src/veins/modules/mobility/traci/NetworkBoundary.h
src/veins/modules/mobility/traci/TraCIConnection.cc
src/veins/modules/mobility/traci/TraCIConnection.h
subprojects/veins_catch/src/traci/NetworkBoundary.cc

Conversion between TraCI and OMNeT++ representations are now handled by a new class, NetworkBoundary.
The interface through TraCIConnection is unchanged for now, the implementation is simply forwarded.
Comes with tests for catch2.
New attempt at #11 , which would no longer merge due to changes in the TraCI api.

Extract coord / angle conversion into helper class

---

src/veins/modules/mac/ieee80211p/Mac1609_4.h

Unfortunately, in f5a3feb3ef88d8ee478e13bde9846d2444a4cedf a compile warning about the order of member initialization was introduced. This commit fixes it.

Fix compile warning

---

examples/veins/omnetpp.ini

Due to disabled undisposed printing potential memory leaks might not be
recognized.
This commit enables the printing of undisposed objects in OMNeT++ to
help developers recognizing those leaks.
See issue #63 for an example.

Enable undisposed printing

---

src/veins/modules/utility/TimerManager.cc
src/veins/modules/utility/TimerManager.h

Use lower case enumerators as per
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-caps.
This fixes #68.

Rename TimerManager enumerators

---

src/veins/modules/mobility/traci/TraCIScenarioManager.cc
src/veins/modules/mobility/traci/TraCIScenarioManager.h

This patchset changes two things:
- Use smart pointers for plain C++ objects owned by the TraCIScenarioManager
- Move the cleanup of the traci connection to TraCIScenarioManager's dtor instead of its finish method. This change allows modules to rely on the traci connection during their finish methods, which was previously only the case for modules that get deleted prior to the simulation ending, e.g. due to teleporting or leaving the ROI. Therefore, it is now possible to record statistics in finish that use traci, such as the CO2 emissions.

Rework traci connection cleanup

---

.gitignore

The current `gitignore` does not handle cmdenv log output in the `tests` subdirectories.

Fix tests gitignore

---

src/veins/modules/utility/Consts80211p.h

The Consts80211p.h file uses SimTime objects but did neither import the omnet header nor qualify their namespace.

add missing omnet include in 802.11p consts

---

CHANGELOG
src/veins/base/connectionManager/BaseConnectionManager.cc
src/veins/base/utils/Coord.h
src/veins/base/utils/FWMath.h
src/veins/base/utils/Move.h
src/veins/base/utils/asserts.h
src/veins/base/utils/veins.h
src/veins/modules/phy/SampledAntenna1D.cc

The current helper for float equality checks does deliver false negatives for numbers that are too large. This PR introduces a new helper that doesn't suffer from these issues and deprecates the old one.

Improve float equality check

---

src/veins/modules/mobility/traci/TraCIBuffer.cc
src/veins/modules/mobility/traci/TraCIBuffer.h
src/veins/modules/mobility/traci/TraCICommandInterface.cc
src/veins/modules/mobility/traci/TraCICommandInterface.h
src/veins/modules/mobility/traci/TraCIScenarioManager.cc

This PR extends the `TraciCommandInterface`, `TraCIBuffer` and some calls to them (in `TraCIScenariomanager`). The makes Veins compatible with Sumo 1.0 (which encodes time as seconds using `double`) and Sumo 0.32 / 0.30 (which encodes time as microseconds using `uint32_t`). Some additional changes in the API were also covered (network boundary format).
The `TraCIBuffer` can now be configured to write `simtime_t` instances either as double or as integer.
The `TraCICommandInterface` now automatically configures itself when `setApiVersion` gets called. All supported API versions and their special types are configured in the `versionConfigs` map. Checking for supported versions is now also done in the `TraCICommandInterface` (as opposed to the `TraCIScenarioManager`). Note that …

Support for Sumo Version 1.0 and 0.32 / 0.30

---

src/veins/modules/utility/TimerManager.cc

This PR adds a break statement to avoid an unwanted implicit fallthrough

Fix accidental implict fallthrough

---

src/veins/modules/mac/ieee80211p/Mac1609_4.cc
src/veins/modules/mac/ieee80211p/Mac1609_4.h

This will enable derived projects, e.g., LanRadio to easily extend the Mac1609_4.

add handleBroadcast handler to Mac

---

subprojects/veins_catch/src/SignalRepresentation.cc

This makes some test descriptions consistent with the values actually used/expected.

Correct values in test description

---

src/veins/modules/utility/TimerManager.cc
src/veins/modules/utility/TimerManager.h

When initially introducing the `TimerManager` one of the functions contained a typo. This PR deprecates this function, introduces a correctly named alternative, and adapts comments.
All tests pass and the exisiting fingerprint is verified.

Fix typo and comments in the TimerManager

---

src/veins/modules/phy/PhyLayer80211p.cc
src/veins/modules/phy/PhyLayer80211p.h

PhyLayer80211p::handleMessage() function was introduced in commit '15a4d3b432cd91a6cec03d788d294f9a7d966ed4' to ensure that non-AirFrame11p frames are not considered by PhyLayer80211p. This can happen only if a global connection manager is used. However, now that Veins VLC has a connection manager of its own AirFrames of different types will not be mixed, hence there is no need for this check.

Remove handleMessage() function of PhyLayer80211p

---

src/veins/modules/mobility/traci/TraCIScenarioManager.cc
src/veins/modules/mobility/traci/TraCIScenarioManager.h

This allows the TraCIScenarioManager to unregister all nics within a vehicle from the corresponding connection managers they are registered to, regardless of the name of the nic.

Unregister from all nics within a vehicle regardless of nic name

---

src/veins/modules/obstacle/ObstacleControl.cc
src/veins/modules/obstacle/ObstacleControl.h

ObstacleControl::finish took a lot of time to clean up on finish (up to minutes for large scenarios with many obstacles). This was due to three nested loops in finish that called erase, which in turn ran the same three nested loops to delete a single obstacle.
This patch simply adds an owning container for each covered obstacle. It contains a unique_ptr as an owner for each obstacle. On finish, the container gets cleaned up, which in turn deletes the Obstacle instances.
ObstacleControl::erase became a bit more complicated because it has to find the owning unique_ptr for the Obstacle to delete. However, ObstacleControl::erase has no longer a caller in the code and
was only left in because it is a public method. (The only previous caller was ObstacleControl::finish).

Fix ObstacleControl::finish overhead.

---

subprojects/veins_catch/src/SimplePathlossModel.cc

The tests were broken by an API change introduced by #117. This adapts the tests to the new
API without any semantic changes.

Fix simple pathloss tests

---

src/veins/modules/utility/TimerManager.cc
src/veins/modules/utility/TimerManager.h

This PR fixes #125 by introducing a check to confirm that the timer has not been cancelled during the callback.
The second commit reworks `TimerHandle` to avoid exposing internal pointers which might lead to issues due to pointer reuse, if a `TimerHandle` is stored by the user beyond the associated timer's lifetime.

Fix timer cancellation

---

Makefile
format-code.sh

This adds targets for code formatting to the makefile.
Formatting the code is as optional as generating the documentation (therefore, there targets). However, since the repository contains config files for clang-format and uncrustify and the code base should be kept consistent (to the upstream repository) in terms of the formatting, especially for further pull requests, I believe it is useful to have these targets.

Code fomatting tools

---

doc/manual/manual.md
doc/manual/timermanager.md
doxy.cfg

This adds content and (doxygen) config for build a user manual from markdown files. It is generated with the normal doxygen documentation and put into the html tree.
As a first entry, I wrote some documentation about the Timermanager, highlighting concepts that are more suitable for a general user manual than pure module documentation.

Add veins user manual buit from markdown files.

---

doc/manual/simsignal_management.md
src/veins/modules/utility/CallableInfo.h
src/veins/modules/utility/SignalManager.h
subprojects/veins_testsims/opp_tests/signalmanager/callbacks_bool.test
subprojects/veins_testsims/opp_tests/signalmanager/callbacks_custom.test
subprojects/veins_testsims/opp_tests/signalmanager/callbacks_double.test
subprojects/veins_testsims/opp_tests/signalmanager/callbacks_long.test
subprojects/veins_testsims/opp_tests/signalmanager/callbacks_simtime.test
subprojects/veins_testsims/opp_tests/signalmanager/callbacks_string.test
subprojects/veins_testsims/opp_tests/signalmanager/callbacks_ulong.test
subprojects/veins_testsims/opp_tests/signalmanager/runtest.sh

This PR add utilities (including documentation and tests) to simplify the usage of OMNeT++ simulation signals.
It works analogously to the TimerManager simplifying usage of self-messages.
Tests are performed using the `opp_test` tool provided by OMNeT++. For more rational and info, see the doc file and tests included in this PR.
Note: If #137 gets merged, the manual page for the features of this PR can easily be included in the user manual from #137 by adding the following to the `doc/manual/manual.md`:
```{doxygen}
* @subpage simsignal_management
```

Add simulation signal management utilities.

---

src/veins/modules/utility/CallableInfo.h

With the explicit template instantiation for the new `lambda_type`, the warning of doxygen goes away, while all tests still pass as expected.

Fix: doxygen warning about recursive relation.

---

format-code.sh

This allows to call the script from an arbitrary directory within veins to format code using the uncrustify config from the root directory (e.g., the subprojects).

Add path to uncrustify config within format script

---

src/veins/modules/mobility/traci/TraCIScenarioManager.h

This PR introduces an accessor to the `TraCIConnection` that can be used by any module to directly interact with the TraCI server.
The code compiles, passes formatting checks and runs the example successfully.

Add traci connection accessor

---

src/veins/modules/mobility/traci/TraCIScenarioManager.cc
src/veins/modules/mobility/traci/TraCIScenarioManager.h

This PR reintroduces a flag that was removed when the signal mechanism for traci initialization was introduced. While the signal allows a loser coupling of components, it does not enable instantaneous checks for the connection status.

Reintroduce flag indicating traci initialization

---

src/veins/modules/mobility/traci/TraCIScenarioManagerForker.cc
src/veins/modules/mobility/traci/TraCIScenarioManagerForker.h
src/veins/modules/mobility/traci/TraCIScenarioManagerForker.ned

This PR introduces a parameter to the `TraCIScenarioManagerForker` which allows modifying the sumo command that is used. This allows to, e.g., use `sumo-gui` or the sumo binary with debug symbols (`sumoD`) instead.

Introduce parameter for modifying forker sumo command

---

src/veins/modules/obstacle/Obstacle.cc
src/veins/modules/obstacle/Obstacle.h
src/veins/modules/obstacle/ObstacleControl.cc
src/veins/modules/obstacle/ObstacleControl.h
src/veins/modules/obstacle/ObstacleControl.ned
src/veins/modules/utility/BBoxLookup.cc
src/veins/modules/utility/BBoxLookup.h

This PR replaces the internal bounding box check of the obstacle shadowing with a much more efficient one, leading to performance improvements of >10x (for scenarios with lots of obstacles).
E.g., in the Paderborn scenario (>50.000 obstacles), around 500 vehicles can be simulated in real time on an i7-7700K, compared to less then 50 with the old code.
Bounding box checks are extracted into the `BBoxLookup` helper class. This class maintains a dense and cache-friendly store of bounding boxes for all obstacles. To find relevant obstacles for a given communication (sender -> receiver), a ray-cast against the bounding boxes of obstacles close to the communication ray is performed. This closeness is modeled via a tile-based layout (similar to the old code in `ObstacleControl`).
In addition, …

Fast obstacle shadowing

---

src/veins/base/phyLayer/BasePhyLayer.cc
src/veins/modules/phy/Decider80211p.cc
src/veins/modules/utility/Consts80211p.h

The commit 2c3ff807020947cceee818fb650c3605c083f7bc removes the complete header definition of the phy, which is wrong according to the IEEE 802.11-2016 standard.
The header length is supposed to be 16 bit + 6 bit = 22 bit which gets fixed by this commit.

Phy header definition

---

src/veins/base/toolbox/Signal.cc
src/veins/base/toolbox/Signal.h

Return a const ref instead of a copy. Does not hurt semantics at all.
This removes some unnecessary copying of instances of the `Spectrum` class, which show up in valgrind even in release mode.

Make Signal::getSpectrum return const ref.

---

src/veins/modules/utility/BBoxLookup.cc

Ther was an off-by-one error if the scenario size is exactly divisble by the cell size.
Then the number of cells would be one to little.
This results in SIGSEV if there was an obstacle touching the secenario border.

Fix: number of cells in BBoxLookup.

---

src/veins/modules/mobility/traci/TraCIScenarioManager.cc
src/veins/modules/mobility/traci/TraCIScenarioManager.h
src/veins/modules/mobility/traci/TraCIScenarioManagerForker.cc
src/veins/modules/mobility/traci/TraCIScenarioManagerForker.h

TraCIScenarioManager can now read the tracie port from an env variable.
The name of the variable is VEINS_TRACI_PORT.
This is only triggered if the port parameter is set to -1.
If this is the case, but VEINS_TRACI_PORT is not set, veins dies.

Add option to configure traci port via env variable.

---

src/veins/modules/utility/SignalManager.h

Modules in the same scope will get freed in an arbitrary order.
Subscriptions between such modules might try to unsubscribe from an
already deleted module. During deletion of the subscribed module, this
relation has already been cleaned up, so unsubscribing is unnecessary in
this case.

Avoid use after free

---

src/veins/base/phyLayer/BasePhyLayer.cc

The Signals's `POA` is set by value, but previously allocated on the heap. This PR passes it directly instead, avoiding manual memory management.

Avoid unnecessary heap allocation

---

src/veins/modules/mac/ieee80211p/Mac1609_4.cc
src/veins/modules/mac/ieee80211p/Mac1609_4.h
src/veins/modules/mac/ieee80211p/Mac1609_4.ned

Following the regular approach of using signals, this PR adds some statistic recording to the (unicast) mac layer. I compiled and tested this with OMNET 5.4.1. It does not change anything in the API or in regard to SUMO.

Add some mac layer statistics

---

src/veins/modules/mobility/traci/TraCIScenarioManager.cc

This PR cleans up the pointer to messages properly on module destruction (i.e., according to the manual). Compiled with OMNET 5.4.1. but should be independent from its version. It does not change anything in the API or in regard to SUMO.

Handle pointer properly on destruction

---

subprojects/veins_testsims/sim/veins_testsims/traci/init.lua

To allow easier use of the Wireshark TraCI dissector.
Tested with Wireshark 3.2.1

Add working doc and set default port for traci dissector.

---

src/veins/modules/mobility/traci/TraCICommandInterface.cc
src/veins/modules/mobility/traci/TraCICommandInterface.h
subprojects/veins_testsims/sim/veins_testsims/traci/omnetpp.ini
subprojects/veins_testsims/src/veins_testsims/traci/TraCITestApp.cc

I tested the new methods with the integrated veins_testsims (SUMO 0.30.0, 0.32.0, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.1) as well as some custom simulation I am currently working on. I used OMNET 5.4.1.  It does not change anything in the API.

Add traci calls for a vehicle type's maximum speed

---

src/veins/modules/mobility/traci/TraCIScenarioManager.cc
src/veins/modules/mobility/traci/TraCIScenarioManager.h
src/veins/modules/mobility/traci/TraCIScenarioManager.ned
subprojects/veins_inet/src/veins_inet/VeinsInetManager.cc
subprojects/veins_inet/src/veins_inet/VeinsInetManager.h

When using the visualization capabilities of INET, the simulation model needs to indicate the addition/removal of nodes at runtime. Otherwise required visualization components are not created and the simulation crashes.
These events shall be emitted by the "visualizationSubjectModule" of the visualizer which usually is the root module of the simulation. This modifies the VeinsInetManager to make its parent module emit these events while also adding a required signal to the TraCIScenarioManager.
Note that the underlying model change signalling mechanism is already integrated into OMNeT++ (See cmodelchange.h), though some additional required events are defined by INET but are planned to be moved there as well.

Fix INET visualization when using veins_inet

---

subprojects/veins_inet3/src/veins_inet/VeinsInetManager.cc

This PR adds missing calls to TraCIScenarioManager methods

VeinsInetManager: add missing calls to superclass methods

---

src/scripts/run.in.py
subprojects/veins_catch/scripts/run.in.py
subprojects/veins_inet/src/scripts/run.in.py
subprojects/veins_inet3/src/scripts/run.in.py
subprojects/veins_testsims/src/scripts/run.in.py

This PR adds callgrind and perf as profiling tools to the run script and also ships the necessary CFLAGS in the makefrag. I tested this with OMNET 5.4.1. It does not change anything in the API or in regard to SUMO.

Add callgrind as profiling tool to run script

---

src/veins/base/modules/BaseMacLayer.h
src/veins/modules/mac/ieee80211p/Mac1609_4.cc
src/veins/modules/mac/ieee80211p/Mac1609_4.h
src/veins/modules/mac/ieee80211p/Mac1609_4.ned

While using the newly implemented unicast mechanism of `Mac1609_4`, I've noticed that there was an `ackErrorRate` parameter, but the dropping mechanism was not implemented. I believe having artificial packet losses is a great feature when testing the behavior of communication protocols that require reliable delivery, so I implemented the mechanism. In addition, I modified the default drop rate value from `0.20` to `0`, as I believe this must be enabled only on purpose.
In addition to the ACK drop mechanism, I implemented the data frame dropping mechanism, enabled by the `frameErrorRate` parameter (default `0`).
Finally, I've added a method to the `BaseMacLayer` class to enable setting the MAC address.

Artificial frame dropping feature for Mac1609_4

---

src/veins/modules/mac/ieee80211p/Mac1609_4.cc
src/veins/modules/mac/ieee80211p/Mac1609_4.h
src/veins/modules/mac/ieee80211p/Mac1609_4.ned

I believe the commit message is self-explanatory :)

Mac1609_4: add signal to inform applications when a unicast transmission failed and record total amount of failures

---

src/veins/modules/mobility/traci/TraCIBuffer.cc
src/veins/modules/mobility/traci/TraCICommandInterface.cc

All other instances of TraCIBuffer::read do not read a type-code before they read the actual data.
TraCIBuffer::read<TraCICoord> was an outlier here, that could lead to unexpected behavior.
Note that TraCIBuffer::read<TraCICoord> is not currently used anywhere in Veins' codebase.
This explains why this error has gone unnoticed for years.
Fixes #179

Fix: Do not read/write typecode from buffer.

---

src/veins/base/utils/FindModule.h
subprojects/veins_inet3/src/veins_inet/VeinsInetManagerBase.cc

This PR includes ~~two~~ three commits.
1. 479df54 introduces a `findSubModules` method which, differently from `findSubModule` retrieves all the instances of a submodule for a parent module. This is useful, for example, when a vehicle has multiple NIC interfaces of the same type (e.g., VLC front and back) and both of them needs to be retrieved
2. 40b037d renames the direct in gate for the 802.11p NIC from `radioIn` to `veins11pRadioIn`. The name `radioIn` is (ab)used by multiple frameworks, making it often impossible to have multiple heterogeneous radio interfaces. For example, `radioIn` is used by INET as well. This is a proposal as 1) I don't know whether this might break backward compatibility and 2) whether there is a more elegant way to do it (e.g., setting the name as a parameter …

Finding multiple submodules and renaming directIn gate

---

src/veins/base/phyLayer/BasePhyLayer.cc
src/veins/modules/mobility/traci/TraCIMobility.h

This PR fixes the error described in #194: If `endSimulation()` is called during the initialization of a module, the veins process crashes with a SIGSEGV.
There are two reasons for this:
1. The `decider` field of the `BasePhyLayer` gets accessed in the `finish` method while it is still `nullptr` (presumably because `BasePhyLayer::initialize` has not run yet). This gets fixed in a770af8
2. The `startAccidentMsg` and `stopAccidentMsg` of `TraciMobility` get accessed in the `finish` method while they still contain undefined contents (pointers to a random location in memory). This gets fixed in 7e40643
Together, these two should make it safe to call OMNeT++'s `endSimulation()` function in the init code of a module (at least the application module). Fixes #194 
TODO: remove error-reproduction …

Fix SIGSEGV if endSimulation is used

---

src/veins/base/connectionManager/ChannelAccess.cc

This PR refactors ChannelAccess::sendToChannel to be more readable with less code duplication.
It also fixes the handling of gate vectors:
- The iteration started at the referenced gate's ID (`radioStart = i->second->getId()`), not at the start of the gate vector. If the referenced `cGate` was not the first gate in the gate vector, the loop would have run past the end of the gate vector.
- In line 105, the loop's end point decreased with each iteration (`g != --radioEnd`).
- For odd-sized gate vectors (≠1), the would have excluded half of the gates.
- For even-sized gate vectors, this would have been an infinite loop.
These bugs have been present for at least 14 years, so I doubt anyone has been using gate vectors in this context. I only noticed them because I was refactoring this method …

Refactor ChannelAccess::sendToChannel

---

src/veins/modules/mobility/traci/TraCICommandInterface.cc
src/veins/modules/mobility/traci/TraCICommandInterface.h
subprojects/veins_testsims/sim/veins_testsims/traci/README
subprojects/veins_testsims/sim/veins_testsims/traci/omnetpp.ini
subprojects/veins_testsims/src/veins_testsims/traci/TraCITestApp.cc

As part of my Master's thesis, I added some missing TraCI vehicle methods to TraCICommandInterface:
* `getSpeed`
* `getAngle`
* `getAcceleration`
* `getDistanceTravelled`
* `getLeader`
Submitting this PR in the hope that this saves someone else time in the future.
Please let me know if you need any changes or revisions!

Add TraCI methods to TraCICommandInterface

---

.cproject

The commit enables the parallel build option in the OMNeT++ IDE by default. The option is configured to use the optimal number of parallel jobs for a build (depending on the used machine)

enable parallel (optimal) build for OMNeT++ IDE

---

src/veins/modules/mobility/traci/TraCIBuffer.h
src/veins/modules/mobility/traci/TraCICommandInterface.cc
src/veins/modules/mobility/traci/TraCICommandInterface.h
subprojects/veins_testsims/sim/veins_testsims/traci/README
subprojects/veins_testsims/sim/veins_testsims/traci/omnetpp.ini
subprojects/veins_testsims/src/veins_testsims/traci/TraCITestApp.cc

This pull request implements a selection of additional TraCI commands I have found useful during my master thesis simulating delivery traffic using SUMO in conjunction with Veins.
- addRoute(): Allows creating a new route with the given edges at runtime (Useful for inserting vehicles at arbitrary positions in the network when no suitable route exists yet. This can be combined with Vehicle::changeTarget to only specify the insertion edge and let SUMO plan the rest of the route for you.)
- Vehicle::changeTarget(): Allow setting a new destination edge which will cause a new route to be calculated.
- Vehicle::getStopState() and Vehicle::isStopped(): Returns whether a vehicle is currently stopped and for what purpose.
- Lane::getWidth(): Get the width of a lane
- Junction::getShape(): Get the …

Additional TraCI commands

---

.github/workflows/linux.yml

This adds a github actions workflow building omnet and veins and running with three versions of sumo:
- the plain ubuntu sumo (currently 1.4.0)
- the ppa version (latest release, currently 1.9.1 and broken for veins)
- the nightly build from the Python package index
The workflow runs on all pushes and PRs to the veins repo and every night to check changes in SUMO. 
Possible optimizations include:
- in the scheduled nightly run only test the nightly sumo
- cache the omnet build results

Adding workflow

---

src/veins/modules/utility/SignalManager.h

This PR disables the exporting of some template classes that prevents correct linking in Windows systems.

SignalManager: do not export template classes to avoid linking problems on Windows systems

---

src/veins/modules/mobility/traci/TraCIScenarioManager.cc

For future versions a more descriptive error message might be helpful; such as "too few/many displayStringKeys".
Including the keys in the error message would also be a nice touch.

Fix moduleDisplayString error message

---

src/veins/modules/utility/TimerManager.cc
src/veins/modules/utility/TimerManager.h
subprojects/veins_testsims/opp_tests/timermanager/cancel.test
subprojects/veins_testsims/opp_tests/timermanager/end.test
subprojects/veins_testsims/opp_tests/timermanager/interval.test
subprojects/veins_testsims/opp_tests/timermanager/oneshot.test
subprojects/veins_testsims/opp_tests/timermanager/runtest.sh
subprojects/veins_testsims/opp_tests/timermanager/start.test

This PR introduces multiple changes:
- add tests for the `TimerManager`
- add the possiblity to define a timers' interval by a functor that is called whenever it is rescheduled. This allows for dynamic timer intervals
- add a second callback option that always passes in the corresponding timers' handle. This makes it easier to cancel timers: From within the timer this is now possible without storing the handle manually.

Improved TimerManager

---

subprojects/veins_catch/.cproject
subprojects/veins_inet/.cproject
subprojects/veins_inet3/.cproject
subprojects/veins_testsims/.cproject

This pull requests enables parallel compilation in all subprojects. The number of used cores is the to _optimal_

Enable parallel IDE build in all subprojects

---

src/veins/modules/mobility/traci/TraCICommandInterface.cc
src/veins/modules/mobility/traci/TraCICommandInterface.h
src/veins/modules/mobility/traci/TraCIScenarioManager.cc
src/veins/modules/mobility/traci/TraCIScenarioManagerForker.ned

This PR improve the current code base by:
- Fixing a bug introduced in 484169eef24085b244bddff2facdfc958ef20c19: the commit added two new parameters to `TraCIScenarioManager.ned` but not to `TraCIScenarioManagerForker.ned` causing the latter to be unusable;
- Enabling multiple building obstacle controllers: this can be useful when using heterogeneous communication technologies that both need the `SimpleObstacleShadowing` model;
- Adding a new TraCI API: adds the `getDistanceRoad` API to obtain the driving distance between two positions on two edges.

Bugfix: missing parameter. Features: multiple obstacle controllers and new TraCI API

---

src/veins/modules/mobility/traci/TraCIScenarioManagerForker.ned

The ```TraCIScenarioManagerForker``` re-declares the ```order``` and ```ignoreUnknownSubscriptionResults``` property in the current master branch.
This leads to an error when the simulation is started and gets fixed with this pull request.

Fix multi definition in TraCIScenarioManagerForker
